version: '3'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: example
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    build: backend
    command: ./wait-for db:5432 -- npm run dev
    environment:
      PORT: 4000
      DATABASE_URL: postgres://example:example@db/example
    volumes:
      - ./backend/src:/app/src
    ports:
      - 4000:4000
    depends_on:
      - db

volumes:
  dbdata:
